#!/bin/bash

# Quick deployment reference
# Run this to see all available commands

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         Modbus RS485 Reader - Deployment Commands         ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Prerequisites:"
echo "   • Ensure .env file exists with your configuration"
echo "   • SSH key authentication setup: ssh-copy-id pi@192.168.20.228"
echo ""
echo "🚀 Deployment Commands:"
echo "   ./deploy.sh init      - Initial deployment (first time)"
echo "   ./deploy.sh update    - Update existing deployment"
echo ""
echo "📊 Monitoring Commands:"
echo "   ./deploy.sh logs      - View real-time logs"
echo "   ./deploy.sh status    - Check application status"
echo ""
echo "⚙️  Control Commands:"
echo "   ./deploy.sh start     - Start the application"
echo "   ./deploy.sh stop      - Stop the application"
echo "   ./deploy.sh restart   - Restart the application"
echo ""
echo "📝 Configuration:"
echo "   • Edit .env file to change settings"
echo "   • Run './deploy.sh update' after changes"
echo ""
echo "🔗 Quick Links:"
echo "   • Repository: https://github.com/thitanatinno/modbus"
echo "   • Server: pi@192.168.20.228"
echo "   • Remote Path: /home/pi/modbus"
echo ""
echo "📚 Documentation:"
echo "   • README.md - Application overview"
echo "   • DEPLOYMENT.md - Detailed deployment guide"
echo "   • ENV_SETUP.md - Environment variables guide"
echo ""
